About page
WildCodeSchool/Hackmasters-project-chef-compass pull request #1
Opened 2023-06-14 12:29 UTC by remy-rm

création de la page About , 
-ajout du dossier model (contient le model class team) , 
-service(contient le dossier pour le service team) et 
-dossier style ( contient les fichier _variables.scss et _animations.scss )

2023-06-15 13:11 UTC, td6904 submitted a review, later dismissed

2023-06-15 14:48 UTC, Benja-san requested changes
If you can change import for use in scss file it is better practice.

2023-06-15 14:48 UTC, Benja-san commented on src/app/pages/about/about.component.html
> +    <section class="team_member" *ngFor="let team of teams" >
your ng for will generate a section for each member, put at the beginning of the member card.
Create an ul an li as well for better referencing

2023-06-15 14:48 UTC, Benja-san commented on src/app/pages/about/about.component.html
> +            <h4>Web Developer</h4>
where is the h3 ?

2023-06-15 15:18 UTC, remy-rm commented on src/app/pages/about/about.component.html
> +            <h4>Web Developer</h4>
i change in h3

2023-06-16 07:54 UTC, td6904 approved these changes

2023-06-16 09:08 UTC, td6904 approved these changes

2023-06-16 09:48 UTC, Benja-san requested changes

2023-06-16 09:48 UTC, Benja-san commented on src/app/app-routing.module.ts
> +  { path: '', component: DemoPageComponent }
path '' leads to two components

2023-06-16 09:48 UTC, Benja-san commented on src/app/pages/about/about.component.scss
>  h1{
please use class with the parent component to wrap all the subjects inside it (can lead to css conflicts)

2023-06-16 11:47 UTC, td6904 approved these changes

2023-06-16 12:36 UTC, Benja-san approved these changes

2023-06-16 12:43 UTC, merged