Navbar
WildCodeSchool/Hackmasters-project-chef-compass pull request #2
Opened 2023-06-14 13:18 UTC by td6904

Merge of navbar v1 to branch 'dev' -  font under buttons on top right not yet set. Global SCSS containing fonts added in a different branch waiting for merge.

2023-06-14 14:12 UTC, Benja-san requested changes

2023-06-14 14:12 UTC, Benja-san commented on src/app/app-routing.module.ts
d'you still need the demoPageComponent?
I don't see any route for your homepage component

2023-06-14 14:12 UTC, Benja-san commented on src/app/app.component.html
>  <router-outlet></router-outlet>
wrap the outlet into a <main> tag ?

2023-06-14 14:12 UTC, Benja-san commented on src/app/navbar/navbar.component.html
> +  <div class="chefs-compass">
This logo is a link to home page or not ?

2023-06-14 14:12 UTC, Benja-san commented on src/app/navbar/navbar.component.html
> +    <div class="mini-burger">
If this code is a placeholder, remove it for now cause it does not display anything

2023-06-14 14:12 UTC, Benja-san commented on src/app/navbar/navbar.component.html
> +  <div class="button-menu">
This should be a nav tag wrapping an ul tag with li tags for each link

2023-06-14 14:12 UTC, Benja-san commented on src/app/navbar/navbar.component.html
> +      <button>
I think those button are links to another pages so remove button tags into link tags

2023-06-15 10:05 UTC, Benja-san requested changes

2023-06-15 10:46 UTC, td6904 commented on src/app/navbar/navbar.component.html
> +        <link />
Which tag are you referring to?

Nav is used for the navigation menu of each link, then each list item is in a list followed by a link tag to wrap the image and p. Personally I thought they were better as buttons. Am I better just to leave it as img and p tags and not wrap them ?

2023-06-15 11:38 UTC, Benja-san approved these changes

2023-06-15 12:56 UTC, remy-rm approved these changes

2023-06-15 13:03 UTC, merged