Responsive favorite security
WildCodeSchool/Hackmasters-project-chef-compass pull request #43
Opened 2023-07-24 14:17 UTC by remy-rm

add security and responsive

2023-07-24 14:21 UTC, ArPimentel approved these changes

2023-07-24 15:26 UTC, Benja-san requested changes

2023-07-24 15:26 UTC, Benja-san commented on src/app/component/recipes-display/recipes-display.component.html
> +            <app-card-recipes
same comment as upside

2023-07-24 15:26 UTC, Benja-san commented on src/app/component/recipes-display/recipes-display.component.html
> +            <app-card-recipes
you know what to do

2023-07-24 15:26 UTC, Benja-san commented on src/app/component/recipes-display/recipes-display.component.html
> +          <div
here as well

2023-07-24 15:26 UTC, Benja-san commented on src/app/component/recipes-display/recipes-display.component.ts
> +      console.error('Invalid recipe category');
remove console logs

2023-07-24 15:26 UTC, Benja-san commented on src/app/component/recipes-display/recipes-display.component.ts
> +      // Scroll left
remove dead code

2023-07-24 15:26 UTC, Benja-san commented on src/app/pages/favorites/favorites.component.ts
> +    this.recipesService.resetParam(); // reset param when component is destroyed
remove dead code

2023-07-24 15:26 UTC, Benja-san commented on src/app/pages/homepage/homepage.component.html
> +    <!--  <img class="contents_img" src="/assets/logo/main-logo.png" alt="" />-->
remove dead code

2023-07-24 15:26 UTC, Benja-san commented on src/app/pages/single-recipe/single-recipe.component.ts
> +                console.log(this.favorite);
remove console log

2023-07-24 15:26 UTC, Benja-san commented on src/app/services/search/search.service.ts
> +    //const firstname = this.http.get<Users[]>(`${this.searchUrl}/users`);
remove dead code

2023-07-24 17:22 UTC, ArPimentel approved these changes

2023-07-25 08:56 UTC, Benja-san requested changes

2023-07-25 08:56 UTC, Benja-san commented on src/app/component/navbar/navbar.component.html
>        </div>
li as well

2023-07-25 11:44 UTC, Benja-san approved these changes

2023-07-25 11:52 UTC, ArPimentel approved these changes

2023-07-25 11:52 UTC, merged