Allrecipes
WildCodeSchool/Hackmasters-project-chef-compass pull request #8
Opened 2023-06-15 10:47 UTC by ArPimentel

Using the HttpClient module to make a GET request to load data from the JSON file for multiple recipes, the page's style and buttons will be implemented soon.

2023-06-15 13:22 UTC, td6904 submitted a review, later dismissed

2023-06-16 08:39 UTC, td6904 approved these changes

2023-06-16 08:39 UTC, td6904 commented
all recipes branch reviewed. Note - awaiting data from data branch for recipe cards to be shown.

2023-06-16 10:09 UTC, Benja-san requested changes

2023-06-16 10:09 UTC, Benja-san commented on src/app/about/about.component.html
> +      <div class="arturo-card">
li tag for all card display.
Add a same class name since you have the same pattern for displaying card part

2023-06-16 10:09 UTC, Benja-san commented on src/app/about/about.component.html
> +            <h4>Web Developer</h4>
where is the h3?

2023-06-16 10:09 UTC, Benja-san commented on src/app/allrecipes/allrecipes.component.html
> +<div class="allrecipes-container">
section tag

2023-06-16 10:09 UTC, Benja-san commented on src/app/allrecipes/allrecipes.component.html
> +  <div class="allrecipes-cards" #carouselContainer>
ul tag

2023-06-16 10:09 UTC, Benja-san commented on src/app/allrecipes/allrecipes.component.html
> +    <div class="recipe-card" *ngFor="let recipe of dishRecipes">
li tag

2023-06-16 10:09 UTC, Benja-san commented on src/app/allrecipes/allrecipes.component.html
> +  <h2 class="allrecipes-title">Dish</h2>
where is the H1 of the page ?

2023-06-16 10:09 UTC, Benja-san commented on src/app/allrecipes/allrecipes.component.html
> +<div class="allrecipes-container">
duplicate changes made for first section to all others

2023-06-16 10:09 UTC, Benja-san commented on src/app/community/community.component.html
> +<script>
that's a no go refactor it in a service and call it inside a ts component

2023-06-16 10:09 UTC, Benja-san commented on src/app/models/Team.model.ts
> +    getImage(): string {
use get image for better application

2023-06-16 10:09 UTC, Benja-san commented on src/app/pages/about/about.component.html
> +    <section class="team_member" *ngFor="let team of teams" >
you'll create a section each time you iterate on the array

2023-06-16 10:09 UTC, Benja-san commented on src/app/pages/about/about.component.html
> +    <section class="team_member" *ngFor="let team of teams" >
ul and li tags needed

2023-06-16 10:09 UTC, Benja-san commented on src/app/pages/about/about.component.scss
> +h1{
use class in order to avoid css conflicts and refactors difficulties

2023-06-16 11:43 UTC, ArPimentel commented on src/app/about/about.component.html
> +<!DOCTYPE html>
It's done

2023-06-20 07:25 UTC, closed without merging